import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'}
class E extends Error{constructor(message:string,public status=400){super(message)}}
const CATEGORIES=['食品','醫護','寢具','衣物','日用品','其他'];const UNITS=['罐','瓶','包','杯','袋','箱','個','公斤','把','顆'];const NON_SUPPLY=['airpod','iphone','macbook','耳機','充電盒','咖啡店'];
function parseJson(raw:string){const clean=raw.trim().replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,'');let data:any;try{data=JSON.parse(clean)}catch{const m=clean.match(/\{[\s\S]*\}/);if(!m)throw new E('AI 回覆不是有效 JSON');data=JSON.parse(m[0])}return data}
function normalizeText(s:string){return s.toLowerCase().replace(/\s+/g,'')}
function stockType(v:string){return v==='frozen'?'Frozen':v==='expiring'?'HasExpiry':v==='no_expiry'?'NoExpiry':['Frozen','HasExpiry','NoExpiry'].includes(v)?v:'NoExpiry'}
function confidenceNumber(v:any){if(typeof v==='number')return Math.max(0,Math.min(1,v));return v==='high'?.9:v==='low'?.3:.6}
function prompt(names:string[]){return `你是志工物資庫存助理。請辨識照片或文字中的公益／救災物資。\n庫存標準品項（name 優先選用）：${names.slice(0,80).join('、')}\n規則：只列物資，忽略背景雜物；非物資或空場景回傳 items=[]；category 只能是食品、醫護、寢具、衣物、日用品、其他；quantity 為正整數；unit 只能是${UNITS.join('、')}；inventory_type 只能是 no_expiry、expiring、frozen；expiry_date 只有清楚辨識時填 YYYY-MM-DD；raw_name 保存包裝品牌；不確定數量用 1 並降低 confidence。生鮮重量需人工確認。\n只回傳 JSON，不要 Markdown：{"items":[{"name":"泡麵","raw_name":"來一客","category":"食品","specification":"1杯","quantity":1,"unit":"杯","inventory_type":"expiring","expiry_date":""}],"confidence":"high"}`}
serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
 const auth=req.headers.get('Authorization');if(!auth)throw new E('缺少登入憑證',401);const c=createClient(Deno.env.get('SUPABASE_URL')??'',Deno.env.get('SUPABASE_ANON_KEY')??'',{global:{headers:{Authorization:auth}}});const{data:{user}}=await c.auth.getUser();if(!user)throw new E('登入已失效',401);const{data:p}=await c.from('profiles').select('*').eq('id',user.id).single();if(!p||!p.is_active)throw new E('帳號未啟用或不存在',403);const b=await req.json();if(p.role_name!=='Admin'&&p.location_id!==b.locationId)throw new E('只能在所屬據點入庫',403);if(!b.inputText?.trim()&&!b.imagePath)throw new E('請輸入描述或上傳照片');const admin=createClient(Deno.env.get('SUPABASE_URL')??'',Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')??'');const[{data:s},{data:defs},{data:syns}]=await Promise.all([admin.from('ai_stock_in_settings').select('*').limit(1).maybeSingle(),admin.from('inventory_item_definition').select('category,item_name,unit,stock_type').eq('is_active',true),admin.from('catalog_synonym').select('synonym,standard_name')]);if(!s?.is_enabled||!s.api_key)throw new E('AI 智慧入庫尚未啟用或未設定 API Key');if(b.imagePath&&!s.supports_image_input)throw new E('目前未開放照片辨識');if(!b.imagePath&&!s.supports_text_input)throw new E('目前未開放文字辨識');let imageData:string|undefined;if(b.imagePath){const{data,error}=await admin.storage.from('ai-stockin').download(b.imagePath);if(error||!data)throw new E('無法讀取上傳圖片');if(data.size>10*1024*1024)throw new E('圖片不得超過 10MB');const bytes=new Uint8Array(await data.arrayBuffer());let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);imageData=`data:${data.type||'image/jpeg'};base64,${btoa(binary)}`}
 const names=(defs??[]).map((x:any)=>x.item_name);const userText=`${prompt(names)}\n使用者描述：${b.inputText||''}`;let raw:string;if(s.provider==='anthropic'){const content:any[]=[];if(imageData){const [header,data]=imageData.split(',');content.push({type:'image',source:{type:'base64',media_type:header.match(/data:(.*);base64/)?.[1]||'image/jpeg',data}})}content.push({type:'text',text:userText});const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'x-api-key':s.api_key,'anthropic-version':'2023-06-01','Content-Type':'application/json'},body:JSON.stringify({model:s.model||'claude-sonnet-4-20250514',max_tokens:s.max_tokens||1500,messages:[{role:'user',content}]})});raw=await r.text();if(!r.ok)throw new E(`Anthropic API ${r.status}: ${raw.slice(0,300)}`);raw=JSON.parse(raw).content?.[0]?.text??raw}else{const content:any[]=[{type:'text',text:userText}];if(imageData)content.push({type:'image_url',image_url:{url:imageData,detail:s.image_detail||'low'}});const endpoint=s.api_endpoint||'https://api.openai.com/v1/chat/completions';const model=s.model||'gpt-4o-mini';const tokenKey=/^(gpt-5|o1|o3|o4)/i.test(model)?'max_completion_tokens':'max_tokens';const r=await fetch(endpoint,{method:'POST',headers:{Authorization:`Bearer ${s.api_key}`,'Content-Type':'application/json'},body:JSON.stringify({model,messages:[{role:'user',content}],temperature:.1,[tokenKey]:s.max_tokens||1500})});const responseText=await r.text();if(!r.ok)throw new E(`OpenAI API ${r.status}: ${responseText.slice(0,300)}`);raw=JSON.parse(responseText).choices?.[0]?.message?.content??responseText}
 const parsed=parseJson(raw);const synonymMap=new Map((syns??[]).map((x:any)=>[normalizeText(x.synonym),x.standard_name]));const defMap=new Map((defs??[]).map((x:any)=>[normalizeText(x.item_name),x]));const items=(Array.isArray(parsed.items)?parsed.items:[]).filter((x:any)=>x&&x.name&&!NON_SUPPLY.some(k=>`${x.name} ${x.raw_name||''}`.toLowerCase().includes(k))).map((x:any)=>{const rawName=String(x.raw_name||x.name).trim();const standard=synonymMap.get(normalizeText(rawName))||synonymMap.get(normalizeText(String(x.name)))||defMap.get(normalizeText(String(x.name)))?.item_name||String(x.name).trim();const def=defMap.get(normalizeText(standard));return{category:CATEGORIES.includes(x.category)?x.category:(def?.category||'其他'),item_name:standard,specification:String(x.specification||'').trim()||null,quantity:Math.max(1,parseInt(x.quantity)||1),unit:UNITS.includes(x.unit)?x.unit:(def?.unit||'個'),stock_type:def?.stock_type||stockType(x.inventory_type),expiration_date:String(x.expiry_date||'').match(/^\d{4}-\d{2}-\d{2}$/)?.[0]||null,safety_stock:0,remark:rawName!==standard?`包裝品名：${rawName}；已對照為 ${standard}`:'請人工核對',confidence:confidenceNumber(parsed.confidence)}});if(!items.length)throw new E('未辨識到可入庫的物資，請重新拍照或改用文字輸入');const logs=[];for(const item of items){const{data,error}=await admin.from('ai_stock_in_log').insert({location_id:b.locationId,input_type:b.imagePath?'Image':'Text',input_text:b.inputText?.trim()||null,input_image_path:b.imagePath||null,suggested_category:item.category,suggested_item_name:item.item_name,suggested_specification:item.specification,suggested_quantity:item.quantity,suggested_unit:item.unit,suggested_stock_type:item.stock_type,suggested_expiration_date:item.expiration_date,suggested_safety_stock:item.safety_stock,suggested_remark:item.remark,confidence:item.confidence,raw_response:raw,operator:p.display_name??p.username}).select().single();if(error)throw new E(error.message);logs.push(data)}return Response.json({success:true,message:`辨識完成，共 ${logs.length} 項，請逐項人工核對`,log:logs[0],logs},{headers:cors})
}catch(e){
 const status=e instanceof E?e.status:500
 const message=e instanceof Error?e.message:'辨識失敗'
 // supabase-js replaces every non-2xx response with a generic
 // "Edge Function returned a non-2xx status code" message.  Keep the actual
 // application error in a normal JSON response so both previously loaded and
 // current frontends can show the useful Chinese explanation.  The original
 // HTTP status is included for diagnostics.
 return new Response(JSON.stringify({success:false,message,status}),{status:200,headers:{...cors,'Content-Type':'application/json'}})
}})
