import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'}
class E extends Error{constructor(message:string,public status=400){super(message)}}
serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
 const auth=req.headers.get('Authorization');if(!auth)throw new E('缺少登入憑證',401);const c=createClient(Deno.env.get('SUPABASE_URL')??'',Deno.env.get('SUPABASE_ANON_KEY')??'',{global:{headers:{Authorization:auth}}});const {data:{user}}=await c.auth.getUser();if(!user)throw new E('登入已失效',401);const {data:me}=await c.from('profiles').select('*').eq('id',user.id).single();if(me?.role_name!=='Admin'||!me.is_active)throw new E('僅管理員可操作',403)
 const admin=createClient(Deno.env.get('SUPABASE_URL')??'',Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')??'');const body=await req.json();const table=body.kind==='line'?'line_notification_settings':'ai_stock_in_settings';let {data:row}=await admin.from(table).select('*').limit(1).maybeSingle();if(!row){const {data}=await admin.from(table).insert({}).select().single();row=data}
 if(body.action==='get')return Response.json({success:true,settings:{...row,channel_access_token:undefined,channel_secret:undefined,api_key:undefined,has_token:!!row.channel_access_token,has_secret:!!row.channel_secret,has_api_key:!!row.api_key}},{headers:cors})
 const p=body.settings??{};const update=body.kind==='line'?{is_enabled:!!p.is_enabled,liff_id:p.liff_id?.trim()||null,notify_low_stock:!!p.notify_low_stock,notify_expiring_soon:!!p.notify_expiring_soon,notify_expired:!!p.notify_expired,...(p.channel_access_token?{channel_access_token:p.channel_access_token}:{}),...(p.channel_secret?{channel_secret:p.channel_secret}:{})}:{is_enabled:!!p.is_enabled,provider:p.provider==='anthropic'?'anthropic':'openai',model:p.model?.trim()||'gpt-4o-mini',api_endpoint:p.api_endpoint?.trim()||null,image_detail:['low','auto','high'].includes(p.image_detail)?p.image_detail:'low',max_tokens:Math.max(100,Math.min(8000,Number(p.max_tokens)||1500)),supports_image_input:!!p.supports_image_input,supports_text_input:!!p.supports_text_input,...(p.api_key?{api_key:p.api_key}:{})};const {error}=await admin.from(table).update({...update,updated_at:new Date().toISOString(),updated_by:me.display_name??me.username}).eq('id',row.id);if(error)throw new E(error.message);return Response.json({success:true,message:'設定已儲存'},{headers:cors})
}catch(e){return new Response(JSON.stringify({success:false,message:e instanceof Error?e.message:'操作失敗'}),{status:e instanceof E?e.status:500,headers:{...cors,'Content-Type':'application/json'}})}})
