import { useEffect, useState, type FormEvent } from 'react'
import { supabase } from '../lib/supabaseClient'

type Notice={ok:boolean;text:string}|null
export function LineSettings(){
 const [s,setS]=useState<any>({is_enabled:false,notify_low_stock:true,notify_expiring_soon:true,notify_expired:true,channel_access_token:'',channel_secret:''}),[notice,setNotice]=useState<Notice>(null),[busy,setBusy]=useState(false)
 useEffect(()=>{supabase.functions.invoke('admin-settings',{body:{action:'get',kind:'line'}}).then(({data})=>data?.settings&&setS((x:any)=>({...x,...data.settings})))},[])
 async function save(e:FormEvent){e.preventDefault();setBusy(true);const{data,error}=await supabase.functions.invoke('admin-settings',{body:{action:'save',kind:'line',settings:s}});setBusy(false);setNotice({ok:!!data?.success,text:data?.message??error?.message??'儲存失敗'})}
 async function test(){setBusy(true);const{data,error}=await supabase.functions.invoke('line-notify',{body:{force:true}});setBusy(false);setNotice({ok:!!data?.success,text:data?.message??error?.message??'傳送失敗'})}
 return <div className="container mt-4"><h2><i className="bi bi-chat-dots"/> LINE 通知設定</h2><hr/>{notice&&<div className={`alert alert-${notice.ok?'success':'danger'}`}>{notice.text}</div>}<div className="row"><div className="col-lg-8"><div className="card shadow-sm"><div className="card-body"><form onSubmit={save}>
  <Switch label="啟用 LINE 通知" checked={s.is_enabled} onChange={(v)=>setS({...s,is_enabled:v})}/><div className="mb-3"><label className="form-label">Channel access token</label><input type="password" className="form-control" value={s.channel_access_token??''} placeholder={s.has_token?'已設定，留空表示不變更':'請貼上 Messaging API token'} onChange={(e)=>setS({...s,channel_access_token:e.target.value})}/></div><div className="mb-3"><label className="form-label">Channel secret</label><input type="password" className="form-control" value={s.channel_secret??''} placeholder={s.has_secret?'已設定，留空表示不變更':'選填'} onChange={(e)=>setS({...s,channel_secret:e.target.value})}/></div>
  <Switch label="低庫存" checked={s.notify_low_stock} onChange={(v)=>setS({...s,notify_low_stock:v})}/><Switch label="30 天內到期" checked={s.notify_expiring_soon} onChange={(v)=>setS({...s,notify_expiring_soon:v})}/><Switch label="已過期" checked={s.notify_expired} onChange={(v)=>setS({...s,notify_expired:v})}/><button className="btn btn-primary me-2" disabled={busy}>儲存設定</button><button type="button" className="btn btn-outline-success" disabled={busy||!s.has_token&&!s.channel_access_token} onClick={()=>void test()}>立即測試傳送</button>
 </form></div></div></div><div className="col-lg-4"><div className="alert alert-info">使用 LINE Messaging API 的 Broadcast endpoint。庫存異動後會自動檢查警示；相同內容會去重複，測試傳送則強制發送。</div></div></div></div>
}
export function AISettings(){
 const[s,setS]=useState<any>({is_enabled:false,api_endpoint:'https://api.openai.com/v1/chat/completions',api_key:'',supports_image_input:true,supports_text_input:true}),[notice,setNotice]=useState<Notice>(null),[busy,setBusy]=useState(false)
 useEffect(()=>{supabase.functions.invoke('admin-settings',{body:{action:'get',kind:'ai'}}).then(({data})=>data?.settings&&setS((x:any)=>({...x,...data.settings})))},[])
 async function save(e:FormEvent){e.preventDefault();setBusy(true);const{data,error}=await supabase.functions.invoke('admin-settings',{body:{action:'save',kind:'ai',settings:s}});setBusy(false);setNotice({ok:!!data?.success,text:data?.message??error?.message??'儲存失敗'})}
 return <div className="container mt-4"><h2><i className="bi bi-stars"/> AI 智慧入庫設定</h2><hr/>{notice&&<div className={`alert alert-${notice.ok?'success':'danger'}`}>{notice.text}</div>}<div className="card shadow-sm"><div className="card-body"><form onSubmit={save}><Switch label="啟用 AI 智慧入庫" checked={s.is_enabled} onChange={(v)=>setS({...s,is_enabled:v})}/><div className="mb-3"><label className="form-label">OpenAI-compatible API endpoint</label><input className="form-control" value={s.api_endpoint??''} onChange={(e)=>setS({...s,api_endpoint:e.target.value})}/></div><div className="mb-3"><label className="form-label">API Key</label><input type="password" className="form-control" value={s.api_key??''} placeholder={s.has_api_key?'已設定，留空表示不變更':'請填入模型 API Key'} onChange={(e)=>setS({...s,api_key:e.target.value})}/></div><Switch label="支援照片輸入" checked={s.supports_image_input} onChange={(v)=>setS({...s,supports_image_input:v})}/><Switch label="支援文字輸入" checked={s.supports_text_input} onChange={(v)=>setS({...s,supports_text_input:v})}/><button className="btn btn-primary" disabled={busy}>儲存設定</button></form></div></div><div className="alert alert-warning mt-3">AI 結果只會建立待確認紀錄；使用者核對並按下確認後才會正式寫入庫存。</div></div>
}
function Switch({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <div className="form-check form-switch mb-3"><input className="form-check-input" type="checkbox" checked={!!checked} onChange={(e)=>onChange(e.target.checked)}/><label className="form-check-label">{label}</label></div>}
