import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { useAuth } from '../hooks/useAuth'
import { AllStockTypes, Roles, stockTypeDisplayName } from '../lib/enums'
import { supabase } from '../lib/supabaseClient'
import { functionErrorMessage } from '../lib/functionError'
import { attachAiPhotoToItem } from '../lib/imageUpload'
import { FlashMessage } from '../components/FlashMessage'
import type { AIStockInLog, SupplyLocation } from '../types/db'

export function AIStockInCreate(){
 const{profile}=useAuth(),[params]=useSearchParams(),navigate=useNavigate();const isAdmin=profile?.role_name===Roles.Admin
 const[locations,setLocations]=useState<SupplyLocation[]>([]),[locationId,setLocationId]=useState<number|null>(profile?.location_id??null),[inputText,setInputText]=useState(''),[image,setImage]=useState<File|null>(null),[log,setLog]=useState<AIStockInLog|null>(null),[form,setForm]=useState<any>(null),[message,setMessage]=useState<{ok:boolean;text:string}|null>(null),[busy,setBusy]=useState(false)
 useEffect(()=>{supabase.from('supply_location').select('*').eq('is_active',true).order('id').then(({data})=>setLocations((data??[])as SupplyLocation[]));const id=params.get('id');if(id)supabase.from('ai_stock_in_log').select('*').eq('id',Number(id)).single().then(({data})=>data&&prepare(data as AIStockInLog))},[params])
 function prepare(x:AIStockInLog){setLog(x);setLocationId(x.location_id);setForm({category:x.suggested_category??'',itemName:x.suggested_item_name??'',specification:x.suggested_specification??'',quantity:x.suggested_quantity??1,unit:x.suggested_unit??'個',stockType:x.suggested_stock_type??'HasExpiry',expirationDate:x.suggested_expiration_date??'',safetyStock:x.suggested_safety_stock??0,remark:x.suggested_remark??''})}
 async function recognize(e:FormEvent){e.preventDefault();if(!locationId){setMessage({ok:false,text:'請選擇據點'});return}setBusy(true);setMessage(null);let imagePath:string|undefined;if(image){if(!image.type.startsWith('image/')||image.size>10*1024*1024){setMessage({ok:false,text:'僅支援 10MB 以下圖片'});setBusy(false);return}const ext=image.name.split('.').pop()?.toLowerCase()||'jpg';imagePath=`${profile?.id}/${crypto.randomUUID()}.${ext}`;const{error}=await supabase.storage.from('ai-stockin').upload(imagePath,image);if(error){setMessage({ok:false,text:error.message});setBusy(false);return}}
  const{data,error}=await supabase.functions.invoke('ai-stockin-recognize',{body:{locationId,inputText,imagePath}});setBusy(false);if(error||!data?.success)setMessage({ok:false,text:data?.message??await functionErrorMessage(error,'辨識失敗')});else{prepare(data.log);setMessage({ok:true,text:data.message})}}
 async function confirm(e:FormEvent){e.preventDefault();setBusy(true);const{data,error}=await supabase.functions.invoke('ai-stockin-confirm',{body:{logId:log?.id,locationId,...form}});setBusy(false);if(error||!data?.success)setMessage({ok:false,text:data?.message??await functionErrorMessage(error,'確認失敗')});else{await attachAiPhotoToItem(data.item,log?.input_image_path);
    // 入庫來源紀錄：AI 智慧入庫也留一筆（無捐贈人），與一般入庫一致。
    if(data.item?.id){await supabase.from('supply_stock_in_log').insert({supply_item_id:data.item.id,location_id:locationId,stock_in_quantity:data.item.quantity,operator:profile?.display_name??profile?.username??null,remark:'AI 智慧入庫'})}
    navigate('/supply-items',{state:{flash:data.message}})}}
 return <div className="container mt-4"><h2><i className="bi bi-stars"/> AI 智慧入庫</h2><hr/>{message&&<div className={`alert alert-${message.ok?'success':'danger'}`}>{message.text}</div>}{!log?<div className="card shadow-sm"><div className="card-body"><form onSubmit={recognize}><div className="mb-3"><label className="form-label">據點 *</label>{isAdmin?<select className="form-select" required value={locationId??''} onChange={(e)=>setLocationId(e.target.value?Number(e.target.value):null)}><option value="">請選擇</option>{locations.map(x=><option key={x.id} value={x.id}>{x.location_name}</option>)}</select>:<input className="form-control" disabled value={locations.find(x=>x.id===locationId)?.location_name??''}/>}</div><div className="mb-3"><label className="form-label">文字描述</label><textarea className="form-control" rows={4} placeholder="例如：白米 10 包，每包 2 公斤，2027-01-01 到期" value={inputText} onChange={(e)=>setInputText(e.target.value)}/></div><div className="mb-3"><label className="form-label">或上傳照片</label><input className="form-control" type="file" accept="image/*" onChange={(e)=>setImage(e.target.files?.[0]??null)}/></div><button className="btn btn-primary btn-lg" disabled={busy||(!inputText.trim()&&!image)}>{busy?'辨識中…':'開始辨識'}</button></form></div></div>:<div className="row"><div className="col-lg-8"><div className="card shadow-sm"><div className="card-header">人工核對辨識結果</div><div className="card-body"><form onSubmit={confirm}><div className="row g-3"><Field label="物資種類" value={form.category} onChange={(v)=>setForm({...form,category:v})}/><Field label="物資名稱" value={form.itemName} onChange={(v)=>setForm({...form,itemName:v})}/><Field label="規格" value={form.specification} onChange={(v)=>setForm({...form,specification:v})}/><Field label="數量" type="number" value={form.quantity} onChange={(v)=>setForm({...form,quantity:v})}/><Field label="單位" value={form.unit} onChange={(v)=>setForm({...form,unit:v})}/><div className="col-md-6"><label className="form-label">庫存分類</label><select className="form-select" value={form.stockType} onChange={(e)=>setForm({...form,stockType:e.target.value})}>{AllStockTypes.map(x=><option key={x} value={x}>{stockTypeDisplayName(x)}</option>)}</select></div>{form.stockType!=='NoExpiry'&&<Field label="有效期限" type="date" value={form.expirationDate} onChange={(v)=>setForm({...form,expirationDate:v})}/>}<Field label="安全庫存" type="number" value={form.safetyStock} onChange={(v)=>setForm({...form,safetyStock:v})}/><div className="col-12"><label className="form-label">備註</label><textarea className="form-control" value={form.remark} onChange={(e)=>setForm({...form,remark:e.target.value})}/></div></div><button className="btn btn-success mt-3" disabled={busy}>確認並正式入庫</button></form></div></div></div><div className="col-lg-4"><div className="alert alert-warning">請務必核對品項、數量、效期。只有按下確認後才會寫入正式庫存。</div></div></div>}</div>
}
function Field({label,value,onChange,type='text'}:{label:string;value:any;onChange:(v:string)=>void;type?:string}){return <div className="col-md-6"><label className="form-label">{label} *</label><input className="form-control" required type={type} min={type==='number'?0:type==='date'?'2000-01-01':undefined} max={type==='date'?'2100-12-31':undefined} value={value} onChange={(e)=>onChange(e.target.value)}/></div>}

export function AIStockInIndex(){const[logs,setLogs]=useState<AIStockInLog[]>([]),[locations,setLocations]=useState<SupplyLocation[]>([]),[keyword,setKeyword]=useState(''),[locationFilter,setLocationFilter]=useState(''),[statusFilter,setStatusFilter]=useState<''|'confirmed'|'pending'>('');useEffect(()=>{Promise.all([supabase.from('ai_stock_in_log').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('supply_location').select('*')]).then(([a,b])=>{setLogs((a.data??[])as AIStockInLog[]);setLocations((b.data??[])as SupplyLocation[])})},[]);const rows=useMemo(()=>{const k=keyword.toLowerCase();return logs.filter(x=>(!locationFilter||x.location_id===Number(locationFilter))&&(!statusFilter||(statusFilter==='confirmed'?x.is_confirmed:!x.is_confirmed))&&`${x.suggested_item_name??''} ${x.input_text??''} ${x.operator??''}`.toLowerCase().includes(k))},[logs,keyword,locationFilter,statusFilter]);function resetFilters(){setKeyword('');setLocationFilter('');setStatusFilter('')}return <div className="container-fluid mt-4"><div className="d-flex justify-content-between"><h2><i className="bi bi-stars"/> AI 智慧入庫紀錄</h2><Link className="btn btn-primary" to="/ai-stockin/create">新增辨識</Link></div><FlashMessage/><div className="card my-3"><div className="card-header bg-light"><i className="bi bi-funnel" /> 篩選條件</div><div className="card-body"><div className="row g-3">
  <div className="col-md-5"><label className="form-label">關鍵字</label><input className="form-control" placeholder="搜尋物資、描述或操作人員" value={keyword} onChange={(e)=>setKeyword(e.target.value)}/></div>
  <div className="col-md-3"><label className="form-label">據點</label><select className="form-select" value={locationFilter} onChange={(e)=>setLocationFilter(e.target.value)}><option value="">全部據點</option>{locations.map(l=><option key={l.id} value={l.id}>{l.location_name}</option>)}</select></div>
  <div className="col-md-3"><label className="form-label">狀態</label><select className="form-select" value={statusFilter} onChange={(e)=>setStatusFilter(e.target.value as ''|'confirmed'|'pending')}><option value="">全部</option><option value="confirmed">已確認</option><option value="pending">待確認</option></select></div>
  <div className="col-md-1 d-flex align-items-end"><button type="button" className="btn btn-secondary w-100" onClick={resetFilters} title="重設"><i className="bi bi-arrow-clockwise" /></button></div>
</div></div></div><div className="card"><div className="table-responsive"><table className="table table-hover mb-0"><thead><tr><th>時間</th><th>據點</th><th>輸入</th><th>建議品項</th><th>信心</th><th>狀態</th><th>操作人員</th><th/></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{new Date(x.created_at).toLocaleString('zh-TW')}</td><td>{locations.find(l=>l.id===x.location_id)?.location_name}</td><td>{x.input_type==='Image'?'照片':x.input_text}</td><td>{x.suggested_item_name}</td><td>{x.confidence==null?'-':`${Math.round(Number(x.confidence)*100)}%`}</td><td><span className={`badge bg-${x.is_confirmed?'success':'secondary'}`}>{x.is_confirmed?'已確認':'待確認'}</span></td><td>{x.operator}</td><td>{!x.is_confirmed&&<Link className="btn btn-outline-primary btn-sm" to={`/ai-stockin/create?id=${x.id}`}>前往確認</Link>}</td></tr>)}</tbody></table></div></div></div>}
